# Generated by Django 2.2.7 on 2019-11-26 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='technology',
            field=models.CharField(default='Django', max_length=20),
            preserve_default=False,
        ),
    ]
