# Generated by Django 2.2.7 on 2019-11-26 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='thumbnail',
            field=models.ImageField(default='img.jpg', upload_to='thumbnails/'),
        ),
    ]
