# Generated by Django 2.2.7 on 2019-11-28 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20191127_1847'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='thumbnail_link',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
